version: '3.9'
services:
  db_docker:
    image: mysql:5.7.44
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - ./api/database/script.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nodecontainer
    restart: always
    volumes:
      - api-data:/var/lib/mysql
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      db_docker:
        condition: service_healthy
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
volumes:
  db_data:
  api-data: